name: Nightly DB Update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * *'

jobs:
  nightly:
    name: Scheduled DB Update
    runs-on: self-hosted
    steps:
      - 
        name: Check Endpoint Access
        if: success()
        run: curl -Lvk ${{ secrets.API_ENDPOINT }}
      -
        name: Checkout
        if: success()
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - 
        name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - 
        name: Build Program
        run: CGO_ENABLED=1 go build -o lu-covid-api .
      - 
        name: Update Database
        run: ./lu-covid-api -update-db
      - 
        name: Commit Database Changes
        if: success()
        run: |-
          git config user.name actions-bot
          git config user.email actions@users.noreply.github.com
          git add database/cases.db
          git commit -m "Update database [automated 🚀]" || exit 0
          git push
